apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: myapp
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  clusterIP: None   # headless service recommended for StatefulSet stable DNS (optional). If you prefer a normal ClusterIP, remove this line.
