apiVersion: v1
kind: Service
metadata:
  name: restapi-lb
  namespace: myapp
spec:
  type: LoadBalancer
  selector:
    app: restapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
